# vi docker-compose.yml
services:
    mongo:
        ports:
            - '27017:27017'
        container_name: mongo-container
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=mongoadmin
            - MONGO_INITDB_ROOT_PASSWORD=bdung
        image: mongo